[build]
builder = "nixpacks"

[deploy]
startCommand = "python3 manage.py migrate && python3 manage.py createsuperuser --noinput && python3 manage.py collectstatic --noinput && gunicorn ruralaccounting.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --threads 4 --worker-class gthread --log-file - --access-logfile - --error-logfile -"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10